"""posts table

Revision ID: 10ce5db6711c
Revises: 634369d28191
Create Date: 2019-04-30 15:59:01.009111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ce5db6711c'
down_revision = '634369d28191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'categories', ['category_id'], ['id'])
    op.add_column('posts', sa.Column('is_appear', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'article', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'is_appear')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
