"""posts table

Revision ID: 122a49f9dbeb
Revises: 5d0e5dbeaf12
Create Date: 2019-04-30 15:46:45.249902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122a49f9dbeb'
down_revision = '5d0e5dbeaf12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'categories', ['category_id'], ['id'])
    op.add_column('posts', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'article_id')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
