"""categories table

Revision ID: 541777f1ba19
Revises: ce0626568882
Create Date: 2019-04-26 10:59:26.166094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541777f1ba19'
down_revision = 'ce0626568882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'categories', ['category_id'], ['id'])
    op.add_column('categories', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'number')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
