"""Articles table

Revision ID: 5b66fcacd849
Revises: ac81a5dc3b46
Create Date: 2019-03-23 21:16:45.357244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b66fcacd849'
down_revision = 'ac81a5dc3b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('seo_link', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_article_create_time'), 'article', ['create_time'], unique=False)
    op.drop_index('ix_article_tag', table_name='article')
    op.drop_index('ix_article_title', table_name='article')
    op.drop_column('article', 'timestamp')
    op.drop_column('article', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('tag', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('article', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_article_title', 'article', ['title'], unique=True)
    op.create_index('ix_article_tag', 'article', ['tag'], unique=False)
    op.drop_index(op.f('ix_article_create_time'), table_name='article')
    op.drop_column('article', 'seo_link')
    op.drop_column('article', 'create_time')
    op.drop_column('article', 'body_html')
    op.drop_column('article', 'body')
    # ### end Alembic commands ###
