"""articles table

Revision ID: 634369d28191
Revises: 122a49f9dbeb
Create Date: 2019-04-30 15:47:11.947088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634369d28191'
down_revision = '122a49f9dbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
