"""Articles table

Revision ID: 844ffdf5db67
Revises: 3564f55c0d1d
Create Date: 2019-03-24 00:49:51.251650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844ffdf5db67'
down_revision = '3564f55c0d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'body')
    # ### end Alembic commands ###
